stages:
  data_ingestion:
    cmd: python src/pipelines/data_ingestion_pipeline.py
    deps:
      - src/constants/paths.py
      - src/utils/helpers.py
      - src/entity/components_config_entity.py
      - src/components/data_ingestion.py
      - data/raw
      - logs/
    outs:
      - artifacts/data_ingestion/

  data_validation:
    cmd: python src/pipelines/data_validation_pipeline.py
    deps:
      - src/constants/paths.py
      - src/utils/helpers.py
      - src/utils/handler.py
      - src/entity/components_config_entity.py
      - src/components/data_validation.py
      - artifacts/data_ingestion/
      - logs/
    outs:
      - artifacts/data_validation/

  data_preprocessing:
    cmd: python src/pipelines/data_preprocessing_pipeline.py
    deps:
      - src/constants/paths.py
      - src/utils/helpers.py
      - src/utils/handler.py
      - src/utils/pre_helper.py
      - src/entity/components_config_entity.py
      - src/components/data_preprocessing.py
      - artifacts/data_ingestion/
      - artifacts/data_validation/
      - logs/
    outs:
      - artifacts/data_preprocessing/
      

  feature_engineering:
    cmd: python src/pipelines/feature_engineering_pipeline.py
    deps:
      - src/constants/paths.py
      - src/utils/helpers.py
      - src/utils/features_engineering_helpers.py
      - src/entity/components_config_entity.py
      - src/components/feature_engineering.py
      - artifacts/data_preprocessing/
      - logs/
    outs:
      - artifacts/feature_engineering/







      


  