# Parameters
TRAIN_TEST_SPLIT_RATIO: 0.2
RANDOM_STATE: 42

# Validation Thresholds
MAX_MISSING_THRESHOLD: 0.05
NUMERICAL_COLUMN_THRESHOLD: 0.05
CATEGORICAL_COLUMN_THRESHOLD: 0.05
MAX_DUPLICATE_THRESHOLD: 0.05
OUTLIER_IQR_THRESHOLD: 1.5
DRIFT_THRESHOLD: 0.05
MIN_CORRELATION_THRESHOLD: 0.10
MAX_SKEWNESS_THRESHOLD: 3.0




